### PR TITLE
Add "is-offline" attribute

### PR DESCRIPTION
**Pull request by nickautomatic**
## Description

This allows us to show or hide things based on network status.

One small downside is that this adds two extra event listeners to `window` when the component connects. These could probably be added conditionally depending on the presence of the `is-offline` attribute, but I wasn't sure it was worth the extra complexity at the moment (since removing them would also be more fiddly if they're not always there).

## Steps to test/reproduce

Use the <code>is-offline</code> attribute to show/hide based on network status:

```html
<hide-when is-offline>This is visible when we're online</hide-when>
<show-when is-offline>...and this is only visible when we're offline</show-when>
```

(I've added a section to `demo.html` for testing purposes)

### CODE REVIEW

**Review by jamesnw — APPROVED** [review]
This is a great addition! 👏 

I echo your concern about the potentially unneeded event listeners. I opened issue #8 to track that separately, since I think it will become more of an issue as we monitor other change events, but also don't think that needs to hold up this contribution.

**Review by mirisuzanne — APPROVED** [review]
This looks good to me. My initial instinct was that maybe it should be `has-network="offline | online"` - so you could toggle either way on either element. I'm not sure that extra complexity is needed for real use-cases, though. This is probably the simpler way to go.

**Comment by jamesnw** [comment]
Good point @mirisuzanne - it does mean you can't combine things like `show if is offline AND language is English". Not sure that's a reasonable use case or not.

**Comment by nickautomatic** [comment]
@jamesnw Maybe I'm missing something, but as far as I can tell you can combine those conditions as things currently stand...?

For example, Chinese (`zh`) isn't in my preferred languages (`navigator.languages`) and so `<hide-when is-offline has-lang="zh">` always displays for me regardless of network status (because the language check is always false), while `<show-when is-offline has-lang="zh">` is always hidden, for the same reason. If I switch them to `has-lang="en"` then they show / hide as expected, depending on network status, since the language check is always true. Let me know if there's something I'm overlooking here though!

**Comment by jamesnw** [comment]
@nickautomatic  🤦  You're right- you can combine those, and the inverse is what I meant to write.

How could you say "show when is _online_ and language is English"? 

It would be possible to nest, with something like-

```html
<show-when has-lang="en">
    <hide-when is-offline>Shown when online with lang=en</hide-when>
</show-when>
```

With the alternate interface from @mirisuzanne, it could be combined into-

```html
<show-when has-network="online" has-lang="en">
    Shown when online with lang=en
</show-when>
```

"Hide when is offline and language is English" would similarly not be possible, if less useful.

Apologies for the incorrect example - Boolean logic can hurt my brain.

**Comment by mirisuzanne** [comment]
@nickautomatic What do you think about using a syntax that could have either offline or online as controls?

**Comment by nickautomatic** [comment]
@mirisuzanne Oh yeah, on reflection, I think that's a really good idea: @jamesnw's example made the benefits of your alternative syntax clearer. My thinking had been that because online status is effectively boolean, the presence or absence of an attribute combined with both `show-when` and `hide-when` covered all logical options. But you're right: the downside of this is that it makes "online" an implicit default state rather than one that can be targeted in the same way as "offline".

So on reflection, I think your syntax is better, since it puts "offline" and "online" on the same logical footing, and might be less confusing in cases where you're combining conditions (like in @jamesnw's example). I did like how `is-offline` reads, but I think that's probably outweighed by these other considerations.

I'd be very happy to open a separate PR with that approach, if you like? (This is all interesting to me so very happy to keep tinkering with this if it's of use / interest 🙂)

**Comment by mirisuzanne** [comment]
@nickautomatic Nice. A new PR (or even an update here) sounds great to me. I think at this point we're all just tinkering - TBD how much use/interest there is in a component like this. :)

**Comment by nickautomatic** [comment]
Ok @mirisuzanne - I've opened [a new PR](https://github.com/oddbird/show-when/pull/9). 👍 Feedback very welcome if you have any further thoughts :)

Fwiw, another nice benefit of your syntax is that it means you can use `show-when` in both cases, rather than the mixture of `show-when` and `hide-when`. As a result, I definitely find it easier to wrap my head around!

**Comment by mirisuzanne** [comment]
Thanks! Closing this one in favor of #9

**Pull request closed without merging**
